# -*- coding: utf-8 -*-
"""desafio-alura-store.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19NCK-9Ordq_Qx1crJyIWy1CCvIjy2iDO
"""

import pandas as pd

# --- 1. CARREGAMENTO DOS DADOS (CÓDIGO BASE) ---
# Certifique-se de que os arquivos loja_1.csv, loja_2.csv, etc., estão na pasta do Colab.
# Se estiverem em subpastas (ex: 'base-de-dados-challenge-1/loja_1.csv'), ajuste os caminhos abaixo.

try:
    # Ajuste o caminho se necessário (ex: '/content/loja_1.csv')
    loja1 = pd.read_csv('loja_1.csv')
    loja2 = pd.read_csv('loja_2.csv')
    loja3 = pd.read_csv('loja_3.csv')
    loja4 = pd.read_csv('loja_4.csv')
    print("Arquivos carregados com sucesso!")
except FileNotFoundError:
    print("Erro: Arquivos não encontrados. Verifique se fez o upload dos CSVs.")

# Lista para facilitar a iteração
lojas = [loja1, loja2, loja3, loja4]
nomes_lojas = ['Loja 1', 'Loja 2', 'Loja 3', 'Loja 4']

# --- 2. TRATAMENTO INICIAL (GARANTIA DE TIPOS) ---
# O Pandas geralmente detecta números automaticamente, mas por segurança,
# garantimos que 'Preço' seja numérico.
for df in lojas:
    # Remove 'R$' se houver e converte para float, caso seja string
    if df['Preço'].dtype == 'object':
        df['Preço'] = df['Preço'].astype(str).str.replace('R$', '', regex=False).str.replace(',', '.')
        df['Preço'] = pd.to_numeric(df['Preço'])

# --- 3. ANÁLISE DE FATURAMENTO ---
print("\n--- Faturamento Total por Loja ---")
faturamentos = []
for i, df in enumerate(lojas):
    faturamento_total = df['Preço'].sum()
    print(f"{nomes_lojas[i]}: R$ {faturamento_total:,.2f}")
    faturamentos.append(faturamento_total)

# --- 4. ANÁLISE DE CATEGORIAS (QUANTIDADE VENDIDA) ---
print("\n--- Categorias Mais Populares por Loja ---")

for i, df in enumerate(lojas):
    # Agrupa por categoria e conta as linhas (vendas)
    contagem_categorias = df['Categoria do Produto'].value_counts()

    print(f"\n{nomes_lojas[i]} - Top 3 Categorias:")
    print(contagem_categorias.head(3))

    # Opcional: Salvar a análise de cada loja em um CSV separado
    nome_arquivo_export = f'analise_categorias_{nomes_lojas[i].replace(" ", "_")}.csv'
    contagem_categorias.to_csv(nome_arquivo_export)
    print(f"-> Dados exportados para: {nome_arquivo_export}")

import matplotlib.pyplot as plt
import pandas as pd

# --- CONFIGURAÇÕES VISUAIS ---
plt.style.use('ggplot') # Estilo bonito para os gráficos
cores_lojas = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728'] # Cores para L1, L2, L3, L4

# --- 1. CÁLCULO DAS NOVAS MÉTRICAS ---

analise_geral = []

print("--- ANÁLISE DETALHADA POR LOJA ---\n")

for i, df in enumerate(lojas):
    nome_loja = nomes_lojas[i]

    # Média de Avaliação
    media_avaliacao = df['Avaliação da compra'].mean()

    # Custo Médio de Frete
    media_frete = df['Frete'].mean()

    # Produtos Mais e Menos Vendidos
    contagem_produtos = df['Produto'].value_counts()
    produto_mais_vendido = contagem_produtos.idxmax()
    qtd_mais_vendido = contagem_produtos.max()
    produto_menos_vendido = contagem_produtos.idxmin()
    qtd_menos_vendido = contagem_produtos.min()

    # Salvar dados para gráficos e relatório
    analise_geral.append({
        'Loja': nome_loja,
        'Faturamento': df['Preço'].sum(), # Recalculando ou pegando da lista anterior
        'Avaliação Média': media_avaliacao,
        'Frete Médio': media_frete,
        'Produto Top': produto_mais_vendido,
        'Produto Bottom': produto_menos_vendido
    })

    print(f"{nome_loja}:")
    print(f"  - Avaliação Média: {media_avaliacao:.2f} / 5.0")
    print(f"  - Frete Médio: R$ {media_frete:.2f}")
    print(f"  - Mais Vendido: {produto_mais_vendido} ({qtd_mais_vendido} unid.)")
    print(f"  - Menos Vendido: {produto_menos_vendido} ({qtd_menos_vendido} unid.)")
    print("-" * 30)

# Convertendo para DataFrame para facilitar plotagem
df_analise = pd.DataFrame(analise_geral)

# --- 2. GERAÇÃO DE GRÁFICOS (VISUALIZAÇÃO) ---

fig, axs = plt.subplots(1, 3, figsize=(18, 5)) # 1 linha, 3 colunas

# Gráfico 1: Faturamento por Loja (Barra)
axs[0].bar(df_analise['Loja'], df_analise['Faturamento'], color=cores_lojas)
axs[0].set_title('Faturamento Total por Loja')
axs[0].set_ylabel('Reais (R$)')
axs[0].ticklabel_format(style='plain', axis='y') # Remove notação científica

# Gráfico 2: Avaliação Média (Linha/Ponto)
axs[1].plot(df_analise['Loja'], df_analise['Avaliação Média'], marker='o', linestyle='-', color='purple', linewidth=2, markersize=8)
axs[1].set_title('Satisfação do Cliente (Avaliação Média)')
axs[1].set_ylim(3.8, 4.2) # Ajuste de escala para ver melhor as diferenças
axs[1].set_ylabel('Nota (0-5)')

# Gráfico 3: Frete Médio (Barra Horizontal)
axs[2].barh(df_analise['Loja'], df_analise['Frete Médio'], color='teal')
axs[2].set_title('Custo Médio de Frete')
axs[2].set_xlabel('Reais (R$)')

plt.tight_layout()
plt.show()

# --- 3. RELATÓRIO FINAL E RECOMENDAÇÃO ---

# Lógica simples para recomendação automática
pior_faturamento = df_analise.loc[df_analise['Faturamento'].idxmin()]
melhor_faturamento = df_analise.loc[df_analise['Faturamento'].idxmax()]
melhor_avaliacao = df_analise.loc[df_analise['Avaliação Média'].idxmax()]
pior_avaliacao = df_analise.loc[df_analise['Avaliação Média'].idxmin()]

print("\n" + "="*50)
print("RELATÓRIO FINAL PARA O SR. JOÃO")
print("="*50)

relatorio = f"""
1. INTRODUÇÃO
O objetivo desta análise foi avaliar o desempenho das quatro lojas para identificar
pontos fortes e fracos, auxiliando na decisão estratégica de qual unidade deve ser vendida (desinvestimento).

2. DESENVOLVIMENTO
Analisamos quatro pilares principais: Faturamento, Mix de Produtos, Satisfação (Avaliação) e Logística (Frete).

* Faturamento: A {melhor_faturamento['Loja']} lidera com R$ {melhor_faturamento['Faturamento']:,.2f}.
  Em contrapartida, a {pior_faturamento['Loja']} teve o menor desempenho financeiro (R$ {pior_faturamento['Faturamento']:,.2f}).

* Satisfação: A {melhor_avaliacao['Loja']} possui a clientela mais satisfeita (Nota {melhor_avaliacao['Avaliação Média']:.2f}),
  enquanto a {pior_avaliacao['Loja']} tem a pior avaliação média ({pior_avaliacao['Avaliação Média']:.2f}).

* Destaques de Produtos:
  Na loja de menor faturamento ({pior_faturamento['Loja']}), o produto mais vendido foi '{pior_faturamento['Produto Top']}'.

3. CONCLUSÃO E RECOMENDAÇÃO
Considerando que o objetivo é vender (se desfazer) da loja com menor potencial atual:

>> RECOMENDA-SE VENDER A: {pior_faturamento['Loja']}

Justificativa:
Esta loja apresentou o menor faturamento total entre todas as analisadas.
Apesar de ter um custo de frete competitivo e uma avaliação razoável,
o volume financeiro é o indicador mais crítico para a sustentabilidade do negócio a curto prazo.
A venda desta unidade permitiria ao Sr. João reinvestir recursos na {melhor_faturamento['Loja']} (Líder de vendas)
ou na {melhor_avaliacao['Loja']} (Líder de qualidade/satisfação).
"""

print(relatorio)